# client.py
#
# This file provides utility functions to interact with the LLM (Large Language Model) backend.
#
# Key Features:
# - Defines functions to generate bullet points and JSON responses using the LLM.
#

import os, requests, hashlib
import json, re

LLM_URL = os.getenv("LLM_URL", "http://localhost:11434")
LLM_MODEL = os.getenv("LLM_MODEL", "gemma2:9b-instruct-q4_0")  # see model picks below

# Generate a hash for a given prompt
def prompt_hash(s: str) -> str:
    return hashlib.sha1(s.encode("utf-8")).hexdigest()[:10]


# Calls the LLM to generate bullet points based on system and user prompts.
#
# Parameters:
# - system: The system prompt to guide the LLM.
# - user: The user prompt to guide the LLM.
# - seed: An integer seed for deterministic generation (default: 7).
# - temperature: A float controlling randomness (default: 0.0).
# Returns:
# - A list of up to 10 bullet points generated by the LLM.

def generate_bullets(system: str, user: str, seed: int = 7, temperature: float = 0.0) -> list[str]:
    payload = {
        "model": LLM_MODEL,
        "options": {"seed": seed, "temperature": temperature},
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
    }
    r = requests.post(f"{LLM_URL}/v1/chat/completions", json=payload, timeout=600)
    r.raise_for_status()
    text = r.json()["choices"][0]["message"]["content"]
    # normalize to bullets
    bullets = []
    for line in text.splitlines():
        line = line.strip(" -•\t")
        if line:
            bullets.append(line)
    return bullets[:10]

# Extract the first JSON object/array from text
def _extract_first_json(text: str):
    # Strip common code fences
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Fallback: find the first {...} or [...] block
    start_candidates = [m.start() for m in re.finditer(r"[\{\[]", text)]
    for start in start_candidates:
        for end in range(len(text), start, -1):
            chunk = text[start:end]
            try:
                return json.loads(chunk)
            except json.JSONDecodeError:
                continue
    return None

# Generate JSON from the LLM
def generate_json(system: str, user: str, seed: int = 7, temperature: float = 0.0) -> dict:
    payload = {
        "model": LLM_MODEL,
        "options": {"seed": seed, "temperature": temperature},
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "stream": False,
    }
    r = requests.post(f"{LLM_URL}/v1/chat/completions", json=payload, timeout=600)
    r.raise_for_status()
    text = r.json()["choices"][0]["message"]["content"]
    parsed = _extract_first_json(text)

    if parsed is None:
        raise json.JSONDecodeError("LLM response could not be parsed as JSON", text, 0)
    return parsed if isinstance(parsed, dict) else {}
